### PR TITLE
#SOARCA-113 feature: run ci jobs on PR to ut-dev branch

### PR DESCRIPTION
**Pull request by SilasGitHub**

### CODE REVIEW

**Comment by SilasGitHub** [comment]
@daw1012345 Maybe add branch protection to avoid accidentally merging on failed test?

**Comment by SilasGitHub** [comment]
For now, I only check code coverage on files in the './caldera' package. If we want to include other packages as well, we'll have to discuss which packages exactly. Some already have a pretty good code coverage so we might not have to write additional unit tests for them to pass this check.

**Comment by daw1012345** [comment]
> For now, I only check code coverage on files in the './caldera' package. If we want to include other packages as well, we'll have to discuss which packages exactly. Some already have a pretty good code coverage so we might not have to write additional unit tests for them to pass this check.

This is fine with me, according to our report we only have to validate the test coverage of our code. Enforcing this for other code is not necessary. The only problem I can foresee is when the auto-generated API gets merged. If it is placed inside this dir, the test coverage test may fail. This is bad, as we don't have to test the auto-generated code.



> @daw1012345 Maybe add branch protection to avoid accidentally merging on failed test?

Good one, it should be enabled now.

**Comment by SilasGitHub** [comment]
> This is fine with me, according to our report we only have to validate the test coverage of our code. Enforcing this for other code is not necessary. The only problem I can foresee is when the auto-generated API gets merged. If it is placed inside this dir, the test coverage test may fail. This is bad, as we don't have to test the auto-generated code.

We can quite easily exclude certain files or packages from the coverage check so that shouldn't be an issue I think

**Review by mpboom — APPROVED** [review]

**Pull request merged**
